export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_UNVERIFIED_USER = "AUTH_UNVERIFIED_USER";
export const AUTH_VERIFIED_AND_REGISTERED = "AUTH_VERIFIED_AND_REGISTERED";
export const SET_REDIRECT_PATH_HOME_USER_NOT_VERIFIED = "SET_REDIRECT_PATH_HOME_USER_NOT_VERIFIED";